#ifndef prax_mobile_h
#define prax_mobile_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace prax_mobile {
#endif // __cplusplus

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int32_t sum(int32_t a, int32_t b);

void start_server(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#ifdef __cplusplus
} // namespace prax_mobile
#endif // __cplusplus

#endif /* prax_mobile_h */
